version: '3.6'
services:
  web:
    build: nginx
    image: haico-nginx
    volumes:
      - static:/srv/haico/static/
      - infoscreen-content:/srv/haico/infoscreen-content/
      - nginx:/etc/nginx/
    ports:
      - "127.0.0.1:8080:80"
    restart: always
  haico:
    build:
      context: .
      args:
        SECRET_KEY: "$SECRET_KEY"
    image: haico
    environment:
      - SECRET_KEY
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
    env_file:
      - .env
    volumes:
      - static:/srv/haico/static/
      - infoscreen-content:/srv/haico/infoscreen-content/
      - databases:/srv/haico/databases/
    expose:
      - 8000
    restart: always
volumes:
  static:
  infoscreen-content:
  databases:
  nginx:
