# Generated by Django 3.2.4 on 2021-06-14 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infoscreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='The name of the infoscreen.')),
            ],
        ),
        migrations.CreateModel(
            name='InfoscreenContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='An url to the hosted file.', verbose_name='file url')),
                ('title', models.TextField(help_text='A title for the content.', verbose_name='title')),
                ('valid_from', models.DateField(blank=True, help_text='The date when this content shouldstart to be shown. Empty means that it should be shown from now on.', null=True, verbose_name='valid from')),
                ('valid_until', models.DateField(blank=True, help_text='The date when this content expires. Empty means it does not expire.', null=True, verbose_name='valid until')),
                ('submission_time', models.DateTimeField(help_text='The time of submission.', verbose_name='submission time')),
                ('group', models.ForeignKey(help_text='The name of the associated group.', on_delete=django.db.models.deletion.RESTRICT, related_name='group', to='auth.group')),
                ('screens', models.ManyToManyField(help_text='The screens this content should be displayed on.', related_name='screens', to='infoscreen.Infoscreen')),
                ('submitter', models.ForeignKey(help_text='The submitter of the content.', on_delete=django.db.models.deletion.RESTRICT, related_name='submitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
